# Generated by Django 4.2.19 on 2025-04-29 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderdetails',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='orderdetails',
            table='order_details',
        ),
    ]
