# Generated by Django 4.2.19 on 2025-04-29 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_subscription_id'),
        ('order_details', '0003_alter_orderdetails_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='order_id',
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(db_column='order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='orders.order'),
        ),
    ]
