# Generated by Django 4.2.19 on 2025-04-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0004_remove_orderdetails_order_id_orderdetails_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='order_item_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
