# Generated by Django 4.2.19 on 2025-04-30 08:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_subscription_id'),
        ('products', '0005_alter_product_image_alter_product_thumbnail'),
        ('order_details', '0005_alter_orderdetails_order_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='order',
            field=models.ForeignKey(
                db_column='order', default=6, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product_id',
            field=models.ForeignKey(db_column='product_id', default=1044,
                                    on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
