# Generated by Django 4.2.19 on 2025-04-30 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0006_alter_orderdetails_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
