# Generated by Django 4.2.19 on 2025-04-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0007_alter_orderdetails_price_at_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
