# Generated by Django 4.2.19 on 2025-05-13 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_subscriptions_start_date'),
        ('subscription_items', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionitems',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='subscriptionitems',
            name='subscription_id',
            field=models.ForeignKey(db_column='subscription_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.subscriptions'),
        ),
    ]
