openapi: 3.0.3
info:
  title: DailyDelish API
  version: 1.0.0
  description: DailyDelish
paths:
  /api/v1/auth/users/:
    get:
      operationId: root_retrieve
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
    post:
      operationId: root_create
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/v1/auth/users/{id}:
    get:
      operationId: root_retrieve_2
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
