# Generated by Django 4.2.19 on 2025-02-25 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_address', '0002_alter_deliveryaddress_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deliveryaddress',
            table='delivery_address',
        ),
    ]
