# Generated by Django 4.2.19 on 2025-02-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_address', '0003_alter_deliveryaddress_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='user_id',
            new_name='user',
        ),
    ]
