# Generated by Django 4.2.19 on 2025-03-31 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_remove_product_available_price_remove_product_mrp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('UNIT', 'Unit'), ('KILOGRAM', 'Kilogram')], default='Kilogram', max_length=20)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('sku', models.CharField(max_length=50)),
                ('product_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
            options={
                'db_table': 'product_variants',
            },
        ),
    ]
