# Generated by Django 4.2.19 on 2025-04-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='frequency',
            field=models.CharField(choices=[('onetime', 'Onetime'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly')], default='onetime', max_length=20),
        ),
    ]
