# Generated by Django 4.2.19 on 2025-05-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptions_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='start_date',
            field=models.DateField(default='2025-05-13'),
        ),
    ]
