# Generated by Django 4.2.19 on 2025-06-17 12:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='pending')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('subscription_id', models.ForeignKey(db_column='subscription_id', on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptions')),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
    ]
