# Generated by Django 4.2.19 on 2025-04-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription_id',
            field=models.ForeignKey(db_column='subscription_id', on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptions'),
        ),
    ]
