# Generated by Django 4.2.19 on 2025-04-11 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
    ]
