# Generated by Django 4.2.19 on 2025-04-11 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='order_status',
        ),
    ]
