# Generated by Django 4.2.19 on 2025-04-17 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptions_frequency'),
        ('orders', '0005_alter_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subscription_id',
            field=models.ForeignKey(blank=True, db_column='subscription_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscriptions'),
        ),
    ]
