# Generated by Django 4.2.19 on 2025-06-17 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='products/images/default.jpg', null=True, upload_to='products/images/')),
                ('thumbnail', models.ImageField(blank=True, default='products/images/default.jpg', null=True, upload_to='products/thumbnails/')),
                ('size', models.CharField(default='1 Unit', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_category.productcategory')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
