# Generated by Django 4.2.19 on 2025-02-25 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=2)),
                ('available_price', models.DecimalField(decimal_places=2, max_digits=2)),
                ('unit', models.CharField(choices=[('UNIT', 'Unit'), ('KILOGRAM', 'Kilogram')], max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_category.productcategory')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
