# Generated by Django 4.2.19 on 2025-03-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_category_id_product_category_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mrp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
    ]
