# Generated by Django 4.2.19 on 2025-04-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_available_price_remove_product_mrp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='1 Unit', max_length=10),
        ),
    ]
