# Generated by Django 4.2.19 on 2025-04-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='products/images/default.jpg', null=True, upload_to='products/images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, default='products/images/default.jpg', null=True, upload_to='products/thumbnails/'),
        ),
    ]
